# Generated by Django 6.0 on 2025-12-26 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Function",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("function_string", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Limits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_index", models.BigIntegerField()),
                ("y_index", models.BigIntegerField()),
                ("limit", models.DecimalField(decimal_places=20, max_digits=20)),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="explorer.function",
                    ),
                ),
            ],
        ),
    ]
