# Generated by Django 6.0 on 2025-12-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("explorer", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="function",
            constraint=models.UniqueConstraint(
                fields=("function_string",),
                name="unique_function_string",
                violation_error_message="This function already exists.",
            ),
        ),
    ]
