# Generated by Django 6.0 on 2025-12-26 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("explorer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Limit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_index", models.PositiveBigIntegerField()),
                ("y_index", models.PositiveBigIntegerField()),
                ("limit", models.DecimalField(decimal_places=20, max_digits=20)),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="explorer.function",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Limits",
        ),
    ]
