# Generated by Django 6.0 on 2026-01-02 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("explorer", "0002_function_unique_function_string"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="function",
            name="unique_function_string",
        ),
    ]
